### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by zorglub78** [eddelbuettel/rinside#38] opened 2019-09-15 07:49 UTC
When I execute, for example, rinside-example0 under valgrind, I have the following:
` **Invalid read of size 8**
==26177==    at 0x4866054: ??? (in /usr/lib/arm-linux-gnueabihf/libarmmem.so)
==26177==  Address 0x74694bc is 12 bytes inside a block of size 19 alloc'd
==26177==    at 0x4847568: malloc (vg_replace_malloc.c:299)
==26177==    by 0x598C7FB: __add_to_environ (setenv.c:215)
==26177==    by 0x4850B67: setenv (vg_replace_strmem.c:2043)
==26177==    by 0x56A4953: RInside::initialize(int, char const* const*, bool, bool, bool) (RInside.cpp:137)
==26177==    by 0x56A5213: RInside::RInside(int, char const* const*, bool, bool, bool) (RInside.cpp:104)
==26177==    by 0x12583: main (rinside_sample0.cpp:14)
`
I am using package r-cran-rinside_0.2.13-1_armhf.deb (yes it runs on a Raspberry P3B+ under raspbian)

Within a source of mine, I get a SIGSEGV when finishing...

Any idea?
Thanks

**Comment by eddelbuettel** [comment] 2019-09-15 13:01
We have seen this when toolchain changes happened. So make sure R, Rcpp and RInside are all compiled with the same compiler version.  Ie try to make sure the .deb packages for R, Rcpp and RInside all match.  If one is older (RInside does not update all that often...) it could be trouble. 

First step: reinstall RIinside from source.  See if it helps. 
Second step: reinstall Rcpp from source, then reinstall RInside from source. That should cover all.

I am closing this as I am fairly certain that this is the cause.  Should you have a reason to reopen, do not hesitate to do so.  Thanks for trying RInside!

**Closed by eddelbuettel** 2019-09-15 13:01 UTC

**Comment by zorglub78** [comment] 2019-09-15 13:54
Installed Rcpp and RInside within R from sources today, after received your message.

But this seems not to solve the problem.

Verified the date in “/usr/local/lib/R/site-library” of Rcpp and RInside, and they are okay (today)

Made a “make clean && make” into “RInside/inst/examples/standard” and the same error appears with valgrind while executing rinside-sample0 (I did not compile the whole RInside out of R, but only the sub-directory examples/standard)

Output of “valgrind ./rinside-sample0”:

==525== Memcheck, a memory error detector

==525== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.

==525== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info

==525== Command: ./rinside_sample0

==525==

==525== Invalid read of size 8

==525==    at 0x4866054: ??? (in /usr/lib/arm-linux-gnueabihf/libarmmem.so)

==525==  Address 0x74694bc is 12 bytes inside a block of size 19 alloc'd

==525==    at 0x4847568: malloc (vg_replace_malloc.c:299)

==525==    by 0x598C7FB: __add_to_environ (setenv.c:215)

==525==    by 0x4850B67: setenv (vg_replace_strmem.c:2043)

==525==    by 0x56A4953: RInside::initialize(int, char const* const*, bool, bool, bool) (RInside.cpp:137)

==525==    by 0x56A5213: RInside::RInside(int, char const* const*, bool, bool, bool) (RInside.cpp:104)

==525==    by 0x12583: main (in /mnt/Thales/RInside/inst/examples/standard/rinside_sample0)

==525==

Hello, world!

==525==

==525== HEAP SUMMARY:

==525==     in use at exit: 18,489,236 bytes in 7,746 blocks

==525==   total heap usage: 25,401 allocs, 17,655 frees, 43,756,653 bytes allocated

==525==

==525== LEAK SUMMARY:

==525==    definitely lost: 0 bytes in 0 blocks

==525==    indirectly lost: 0 bytes in 0 blocks

==525==      possibly lost: 3,884 bytes in 1 blocks

==525==    still reachable: 18,485,352 bytes in 7,745 blocks

==525==         suppressed: 0 bytes in 0 blocks

==525== Rerun with --leak-check=full to see details of leaked memory

==525==

==525== For counts of detected and suppressed errors, rerun with: -v

==525== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 43 from 12)

 

Thanks for your help

**Comment by eddelbuettel** [comment] 2019-09-15 14:01
My bad -- I had missed the initial valgrind use there.  

Well, if you think something is wrong, go and prepare a PR.  Otherwise the code has worked _as-is_ on lots of platforms for lots of users for many years, and has not seen many changes.  Of course, there could be bugs hiding, but if you think you have one feel free to debug further.

**Comment by zorglub78** [comment] 2019-09-15 14:06
Sorry, but english is not my native language (I’m a froggy ;o)… What is PR ?

 

Thanks

**Comment by eddelbuettel** [comment] 2019-09-15 14:59
Please see https://help.github.com/en/articles/about-pull-requests

When you reply by email, do me a favour and edit out the quoted text.  It all goes back to the webinterface at https://github.com/eddelbuettel/rinside/issues/38 and just fills it with noise.

**Comment by eddelbuettel** [comment] 2019-09-15 15:57
> I did not compile the whole RInside out of R

That is a mistake.  And as I said in the first post, make sure _all_ is compiled consistently.  

The example loads code from the package.  So rebuild the package.

**Comment by zorglub78** [comment] 2019-09-16 07:15
Done « install.packages(‘Rcpp’) » and « install.packages(‘RInside’) »

 

Into « RInside/inst/examples/standard” done a “make clean && make” 

 

Then “valgrind ./rinside_sample0”

The same access error appears:

“==947== Invalid read of size 8

==947==    at 0x4866054: ??? (in /usr/lib/arm-linux-gnueabihf/libarmmem.so)

==947==  Address 0x74694bc is 12 bytes inside a block of size 19 alloc'd

==947==    at 0x4847568: malloc (vg_replace_malloc.c:299)

==947==    by 0x598C7FB: __add_to_environ (setenv.c:215)

==947==    by 0x4850B67: setenv (vg_replace_strmem.c:2043)

==947==    by 0x56A4953: RInside::initialize(int, char const* const*, bool, bool, bool) (RInside.cpp:137)

==947==    by 0x56A5213: RInside::RInside(int, char const* const*, bool, bool, bool) (RInside.cpp:104)

==947==    by 0x12583: main (rinside_sample0.cpp:14)”

 

What am I doing wrong?

 

Thanks for help…

**Comment by eddelbuettel** [comment] 2019-09-16 11:51
What happens when you don't use valgrind?  

In any event, I can't replicate:

```sh
edd@rob:~/git/rinside/inst/examples/standard(master)$ valgrind ./rinside_sample0
==6311== Memcheck, a memory error detector
==6311== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==6311== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==6311== Command: ./rinside_sample0
==6311== 
Hello, world!
==6311== 
==6311== HEAP SUMMARY:
==6311==     in use at exit: 50,349,955 bytes in 9,712 blocks
==6311==   total heap usage: 27,763 allocs, 18,051 frees, 86,012,613 bytes allocated
==6311== 
==6311== LEAK SUMMARY:
==6311==    definitely lost: 0 bytes in 0 blocks
==6311==    indirectly lost: 0 bytes in 0 blocks
==6311==      possibly lost: 0 bytes in 0 blocks
==6311==    still reachable: 50,349,955 bytes in 9,712 blocks
==6311==                       of which reachable via heuristic:
==6311==                         newarray           : 4,264 bytes in 1 blocks
==6311==         suppressed: 0 bytes in 0 blocks
==6311== Rerun with --leak-check=full to see details of leaked memory
==6311== 
==6311== For counts of detected and suppressed errors, rerun with: -v
==6311== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
edd@rob:~/git/rinside/inst/examples/standard(master)$ 
```

I don't have a raspian and cannot help you.  There is no reproducible _bug_ reported anywhere.

**Comment by eddelbuettel** [comment] 2019-09-16 12:14
If your problem is

>  Within a source of mine, I get a SIGSEGV when finishing...

then you are looking at the wrong problem.  RInside is not itself buggy.

**Comment by zorglub78** [comment] 2019-09-16 14:57
I’ve got the solution !

In fact it was a mistake due to LD_LIBRARY_PATH (2 different versions of libcc dynamic library)…

 

Thanks for your help

**Comment by eddelbuettel** [comment] 2019-09-16 14:59
Yay!  That would do it too.  

I wish we could get to better errors in cases like this.  But testing across platforms helps to keep the setup in check.   Glad to know it work now.
